/*
 * game_config.c — TOML-only game config loader.
 *
 * The legacy whitespace-separated `.cfg` format has been retired. All
 * game projects now use `game.toml`, parsed by tomlc99 (see toml.h).
 * The schema mirrors what nesrecomp ships:
 *
 *     [game]
 *     output_prefix      = "sonic2"
 *     annotations        = "annotations_from_disasm.csv"
 *     vblank_yield_addr  = 0x002998        # optional
 *     allow_68020_branch = false
 *     jump_table_autodiscovery = false
 *     trap0_inline_service_word = false
 *     discovery_files    = ["sonic2.discovery.toml"]   # merged in
 *
 *     [functions]
 *     extra     = [0x000206, 0x000408, 0x000F54]
 *     blacklist = []
 *
 *     [[jump_table]]
 *     start  = 0x000468
 *     end    = 0x000484
 *     stride = 2
 *     format = "pcrel16"          # or "abs"
 *
 *     [[protected_range]]
 *     lo = 0x010000
 *     hi = 0x010040
 *
 * Discovery files (auto-generated by gen_disasm_labels.py /
 * gen_disasm_jumptables.py / etc.) are themselves TOML and are merged
 * into the parent config — only their `[functions].extra`,
 * `[functions].blacklist`, `[[jump_table]]`, and `[[protected_range]]`
 * arrays contribute. A discovery file's `[game]` table is ignored.
 */
#include "game_config.h"
#include "toml.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ------------------------------------------------------------------ */
/* Dynamic-array growth (unchanged from the cfg era).                 */

static void *grow_to_fit(void *arr, int *cap_ptr, int count, size_t elem_size) {
    if (count < *cap_ptr) return arr;
    int new_cap = *cap_ptr ? *cap_ptr * 2 : 64;
    while (new_cap <= count) new_cap *= 2;
    void *p = realloc(arr, (size_t)new_cap * elem_size);
    if (!p) {
        fprintf(stderr, "game_config: out of memory growing to %d entries\n", new_cap);
        abort();
    }
    *cap_ptr = new_cap;
    return p;
}

static void append_extra_func(GameConfig *cfg, uint32_t addr) {
    cfg->extra_funcs = grow_to_fit(cfg->extra_funcs,
                                   &cfg->extra_func_cap,
                                   cfg->extra_func_count,
                                   sizeof(uint32_t));
    cfg->extra_funcs[cfg->extra_func_count++] = addr;
}

static void append_extra_seed(GameConfig *cfg, uint32_t addr) {
    cfg->extra_seeds = grow_to_fit(cfg->extra_seeds,
                                   &cfg->extra_seed_cap,
                                   cfg->extra_seed_count,
                                   sizeof(uint32_t));
    cfg->extra_seeds[cfg->extra_seed_count++] = addr;
}

static void append_blacklist(GameConfig *cfg, uint32_t addr) {
    cfg->blacklist = grow_to_fit(cfg->blacklist,
                                 &cfg->blacklist_cap,
                                 cfg->blacklist_count,
                                 sizeof(uint32_t));
    cfg->blacklist[cfg->blacklist_count++] = addr;
}

static void append_protected_range(GameConfig *cfg, uint32_t lo, uint32_t hi) {
    cfg->protected_ranges = grow_to_fit(cfg->protected_ranges,
                                        &cfg->protected_range_cap,
                                        cfg->protected_range_count,
                                        sizeof(ProtectedRange));
    int idx = cfg->protected_range_count++;
    cfg->protected_ranges[idx].lo = lo;
    cfg->protected_ranges[idx].hi = hi;
}

static void append_jump_table(GameConfig *cfg, uint32_t start, uint32_t end,
                              uint32_t stride, JumpTableFormat fmt) {
    cfg->jump_tables = grow_to_fit(cfg->jump_tables,
                                   &cfg->jump_table_cap,
                                   cfg->jump_table_count,
                                   sizeof(JumpTableEntry));
    JumpTableEntry *e = &cfg->jump_tables[cfg->jump_table_count++];
    e->start_addr   = start;
    e->end_addr     = end;
    e->stride_bytes = stride ? stride : 4;
    e->format       = fmt;
}

/* Resolve a relative path against a base file's directory. */
static void resolve_path(const char *base, const char *rel, char *out, int out_size) {
    const char *slash  = strrchr(base, '/');
    const char *bslash = strrchr(base, '\\');
    const char *sep    = slash > bslash ? slash : bslash;
    if (sep) {
        int dir_len = (int)(sep - base) + 1;
        snprintf(out, out_size, "%.*s%s", dir_len, base, rel);
    } else {
        strncpy(out, rel, out_size - 1);
        out[out_size - 1] = '\0';
    }
}

static int cmp_u32(const void *a, const void *b) {
    uint32_t x = *(const uint32_t *)a, y = *(const uint32_t *)b;
    return (x > y) - (x < y);
}

/* Load a flat text file of hex instruction-start addresses (one per line, '#'
 * comments allowed) into cfg->code_addrs, then sort for binary search. This
 * is the disasm "is this code?" oracle used to gate boundary-split promotion.
 * Returns the number of addresses loaded. */
static int load_code_addrs_file(GameConfig *cfg, const char *path) {
    FILE *fp = fopen(path, "r");
    if (!fp) return 0;
    char line[64];
    while (fgets(line, sizeof(line), fp)) {
        char *p = line;
        while (*p == ' ' || *p == '\t') p++;
        if (*p == '#' || *p == '\n' || *p == '\r' || *p == '\0') continue;
        uint32_t a = (uint32_t)strtoul(p, NULL, 16);
        cfg->code_addrs = grow_to_fit(cfg->code_addrs, &cfg->code_addr_cap,
                                      cfg->code_addr_count, sizeof(uint32_t));
        cfg->code_addrs[cfg->code_addr_count++] = a;
    }
    fclose(fp);
    if (cfg->code_addr_count > 0)
        qsort(cfg->code_addrs, (size_t)cfg->code_addr_count,
              sizeof(uint32_t), cmp_u32);
    return cfg->code_addr_count;
}

/* ------------------------------------------------------------------ */
/* tomlc99 read helpers.                                              */

static bool toml_string_into(toml_table_t *tbl, const char *key,
                             char *dst, size_t dst_size)
{
    toml_datum_t d = toml_string_in(tbl, key);
    if (!d.ok) return false;
    strncpy(dst, d.u.s, dst_size - 1);
    dst[dst_size - 1] = '\0';
    free(d.u.s);
    return true;
}

static bool toml_bool_or(toml_table_t *tbl, const char *key, bool def) {
    toml_datum_t d = toml_bool_in(tbl, key);
    return d.ok ? (bool)d.u.b : def;
}

static uint32_t toml_u32_or(toml_table_t *tbl, const char *key, uint32_t def) {
    toml_datum_t d = toml_int_in(tbl, key);
    return d.ok ? (uint32_t)d.u.i : def;
}

static JumpTableFormat parse_jt_format(const char *s) {
    if (!s) return JT_FMT_ABS_L;
    if (strcmp(s, "pcrel16") == 0 || strcmp(s, "pcrel_w") == 0)
        return JT_FMT_PCREL_W;
    if (strcmp(s, "bra_w")   == 0) return JT_FMT_BRA_W;
    if (strcmp(s, "bra_s")   == 0) return JT_FMT_BRA_S;
    return JT_FMT_ABS_L;   /* default for "abs" and unknown */
}

/* ------------------------------------------------------------------ */
/* Discovery-file merge: pulls in [functions].extra, [functions].blacklist,
 * [[jump_table]], [[protected_range]] from a child TOML. The child's
 * [game] section is ignored — discovery is data, not policy. */

static bool merge_toml(GameConfig *cfg, toml_table_t *root, const char *src_path);

static bool load_and_merge_toml(GameConfig *cfg, const char *path) {
    FILE *f = fopen(path, "r");
    if (!f) {
        fprintf(stderr, "[GameConfig] cannot open '%s'\n", path);
        return false;
    }
    char errbuf[256];
    toml_table_t *root = toml_parse_file(f, errbuf, sizeof(errbuf));
    fclose(f);
    if (!root) {
        fprintf(stderr, "[GameConfig] TOML parse error in '%s': %s\n", path, errbuf);
        return false;
    }
    bool ok = merge_toml(cfg, root, path);
    toml_free(root);
    return ok;
}

static bool merge_toml(GameConfig *cfg, toml_table_t *root, const char *src_path) {
    /* [functions].extra (array of ints) */
    toml_table_t *funcs = toml_table_in(root, "functions");
    if (funcs) {
        toml_array_t *extra = toml_array_in(funcs, "extra");
        if (extra) {
            int n = toml_array_nelem(extra);
            for (int i = 0; i < n; i++) {
                toml_datum_t d = toml_int_at(extra, i);
                if (d.ok) append_extra_func(cfg, (uint32_t)d.u.i);
            }
        }
        toml_array_t *seeds = toml_array_in(funcs, "extra_seeds");
        if (seeds) {
            int n = toml_array_nelem(seeds);
            for (int i = 0; i < n; i++) {
                toml_datum_t d = toml_int_at(seeds, i);
                if (d.ok) append_extra_seed(cfg, (uint32_t)d.u.i);
            }
        }
        toml_array_t *bl = toml_array_in(funcs, "blacklist");
        if (bl) {
            int n = toml_array_nelem(bl);
            for (int i = 0; i < n; i++) {
                toml_datum_t d = toml_int_at(bl, i);
                if (d.ok) append_blacklist(cfg, (uint32_t)d.u.i);
            }
        }
    }

    /* [[jump_table]] */
    toml_array_t *jts = toml_array_in(root, "jump_table");
    if (jts) {
        int n = toml_array_nelem(jts);
        for (int i = 0; i < n; i++) {
            toml_table_t *t = toml_table_at(jts, i);
            if (!t) continue;
            uint32_t start  = toml_u32_or(t, "start",  0);
            uint32_t end    = toml_u32_or(t, "end",    0);
            uint32_t stride = toml_u32_or(t, "stride", 4);
            char fmt[32] = {0};
            toml_string_into(t, "format", fmt, sizeof(fmt));
            append_jump_table(cfg, start, end, stride, parse_jt_format(fmt));
        }
    }

    /* [[protected_range]] */
    toml_array_t *pr = toml_array_in(root, "protected_range");
    if (pr) {
        int n = toml_array_nelem(pr);
        for (int i = 0; i < n; i++) {
            toml_table_t *t = toml_table_at(pr, i);
            if (!t) continue;
            uint32_t lo = toml_u32_or(t, "lo", 0);
            uint32_t hi = toml_u32_or(t, "hi", 0);
            append_protected_range(cfg, lo, hi);
            printf("[GameConfig] Protected range: $%06X-$%06X (from %s)\n",
                   lo, hi, src_path ? src_path : "<root>");
        }
    }

    return true;
}

/* ------------------------------------------------------------------ */

void game_config_init_empty(GameConfig *cfg) {
    memset(cfg, 0, sizeof(*cfg));
}

void game_config_free(GameConfig *cfg) {
    free(cfg->jump_tables);
    free(cfg->extra_funcs);
    free(cfg->extra_seeds);
    free(cfg->blacklist);
    free(cfg->protected_ranges);
    free(cfg->code_addrs);
    memset(cfg, 0, sizeof(*cfg));
}

bool game_config_load(GameConfig *cfg, const char *path) {
    /* Reject the legacy .cfg path with a clear migration message. */
    size_t plen = strlen(path);
    if (plen >= 4 && strcmp(path + plen - 4, ".cfg") == 0) {
        fprintf(stderr,
            "[GameConfig] '%s' is the legacy .cfg format which has been "
            "retired. Pass the new game.toml instead. See tools/migrate_cfg.py "
            "or the migration plan for details.\n", path);
        return false;
    }

    game_config_init_empty(cfg);

    FILE *f = fopen(path, "r");
    if (!f) {
        fprintf(stderr, "[GameConfig] cannot open '%s'\n", path);
        return false;
    }
    char errbuf[256];
    toml_table_t *root = toml_parse_file(f, errbuf, sizeof(errbuf));
    fclose(f);
    if (!root) {
        fprintf(stderr, "[GameConfig] TOML parse error in '%s': %s\n", path, errbuf);
        return false;
    }

    /* [game] — scalars + discovery_files */
    toml_table_t *game = toml_table_in(root, "game");
    if (game) {
        toml_string_into(game, "output_prefix",
                         cfg->output_prefix, sizeof(cfg->output_prefix));
        toml_string_into(game, "annotations",
                         cfg->annotations_path, sizeof(cfg->annotations_path));
        cfg->vblank_yield_addr        = toml_u32_or(game, "vblank_yield_addr", 0);
        cfg->allow_68020_branch       = toml_bool_or(game, "allow_68020_branch", false);
        cfg->jump_table_autodiscovery = toml_bool_or(game, "jump_table_autodiscovery", false);
        cfg->function_aliases         = toml_bool_or(game, "function_aliases", false);
        cfg->async_resume_entries     = toml_bool_or(game, "async_resume_entries", false);
        cfg->trap0_inline_service_word = toml_bool_or(
            game, "trap0_inline_service_word", false);

        /* code_addrs_file: flat text list (one hex instruction-start addr per
         * line) — the disasm "is this code?" oracle that gates boundary-split
         * promotion. Loaded into cfg->code_addrs (sorted). */
        {
            char caf[256] = {0};
            toml_string_into(game, "code_addrs_file", caf, sizeof(caf));
            if (caf[0]) {
                char caf_path[512];
                resolve_path(path, caf, caf_path, sizeof(caf_path));
                int n = load_code_addrs_file(cfg, caf_path);
                if (n > 0)
                    fprintf(stderr, "[GameConfig] code_addrs_file '%s': %d "
                            "code addresses (boundary-split data-gate ON)\n",
                            caf_path, n);
                else
                    fprintf(stderr, "[GameConfig] WARNING: code_addrs_file "
                            "'%s' empty/unreadable; data-gate OFF\n", caf_path);
            }
        }

        /* discovery_files: array of relative TOML paths to merge in. */
        toml_array_t *df = toml_array_in(game, "discovery_files");
        if (df) {
            int n = toml_array_nelem(df);
            for (int i = 0; i < n; i++) {
                toml_datum_t d = toml_string_at(df, i);
                if (!d.ok) continue;
                char child_path[512];
                resolve_path(path, d.u.s, child_path, sizeof(child_path));
                int before_funcs = cfg->extra_func_count;
                int before_jt    = cfg->jump_table_count;
                if (load_and_merge_toml(cfg, child_path)) {
                    fprintf(stderr,
                        "[GameConfig] merged '%s': +%d extra_funcs, +%d jump_tables\n",
                        child_path,
                        cfg->extra_func_count - before_funcs,
                        cfg->jump_table_count  - before_jt);
                }
                free(d.u.s);
            }
        }
    }

    /* [ram_layout] — per-game RAM addresses + state-shape constants.
     * Required for any game whose generated code links against shared
     * runner code that reads g_game_layout. Missing keys default to 0,
     * which the runtime treats as "feature disabled" where applicable
     * (e.g., plc_pending_addr=0 disables the periodic PLC hook). */
    toml_table_t *layout = toml_table_in(root, "ram_layout");
    if (layout) {
        GameRamLayoutCfg *L = &cfg->ram_layout;
        L->present              = true;
        L->game_mode_addr       = toml_u32_or(layout, "game_mode",      0);
        L->vint_runcount_addr   = toml_u32_or(layout, "vint_runcount",  0);
        L->vint_routine_addr    = toml_u32_or(layout, "vint_routine",   0);
        L->plc_pending_addr     = toml_u32_or(layout, "plc_pending",    0);
        L->initial_ssp          = toml_u32_or(layout, "initial_ssp",    0);
        L->vbla_stack           = toml_u32_or(layout, "vbla_stack",     0);
        L->intr_stack           = toml_u32_or(layout, "intr_stack",     0);
        L->player_object_addr   = toml_u32_or(layout, "player_object",  0);

        toml_array_t *lm = toml_array_in(layout, "level_modes");
        if (lm) {
            int n = toml_array_nelem(lm);
            if (n > GAMECFG_LEVEL_MODES_MAX) n = GAMECFG_LEVEL_MODES_MAX;
            for (int i = 0; i < n; i++) {
                toml_datum_t d = toml_int_at(lm, i);
                if (d.ok) L->level_modes[L->level_mode_count++] = (uint8_t)d.u.i;
            }
        }
        printf("[GameConfig] [ram_layout] loaded: game_mode=$%06X vint_runcount=$%06X "
               "vint_routine=$%06X plc=$%06X initial_ssp=$%06X vbla_stack=$%06X "
               "intr_stack=$%06X player=$%06X level_modes=%d\n",
               L->game_mode_addr, L->vint_runcount_addr, L->vint_routine_addr,
               L->plc_pending_addr, L->initial_ssp, L->vbla_stack, L->intr_stack,
               L->player_object_addr, L->level_mode_count);
    }

    /* Inline [functions] / [[jump_table]] / [[protected_range]] from
     * the root document — same merge function as the discovery files. */
    bool ok = merge_toml(cfg, root, path);
    toml_free(root);

    if (cfg->blacklist_count > 0)
        printf("[GameConfig] %d blacklisted addresses loaded\n", cfg->blacklist_count);

    return ok;
}

bool game_config_is_blacklisted(const GameConfig *cfg, uint32_t addr) {
    for (int i = 0; i < cfg->blacklist_count; i++)
        if (cfg->blacklist[i] == addr)
            return true;
    return false;
}

bool game_config_is_known_code(const GameConfig *cfg, uint32_t addr) {
    /* No oracle loaded → gating disabled, everything is "code" (prior behavior). */
    if (!cfg || cfg->code_addr_count == 0) return true;
    return bsearch(&addr, cfg->code_addrs, (size_t)cfg->code_addr_count,
                   sizeof(uint32_t), cmp_u32) != NULL;
}

bool game_config_is_protected(const GameConfig *cfg, uint32_t addr) {
    for (int i = 0; i < cfg->protected_range_count; i++)
        if (addr >= cfg->protected_ranges[i].lo && addr <= cfg->protected_ranges[i].hi)
            return true;
    return false;
}

bool game_config_emit_layout(const GameConfig *cfg, const char *output_path) {
    if (!cfg->ram_layout.present) {
        fprintf(stderr,
            "[GameConfig] %s: refusing to emit layout — game.toml has no "
            "[ram_layout] table. Add one before regenerating.\n",
            output_path);
        return false;
    }
    FILE *f = fopen(output_path, "w");
    if (!f) {
        fprintf(stderr, "[GameConfig] cannot write '%s'\n", output_path);
        return false;
    }

    const GameRamLayoutCfg *L = &cfg->ram_layout;
    fprintf(f,
        "/* %s — AUTO-GENERATED by GenesisRecomp from game.toml. DO NOT EDIT. */\n"
        "#include \"game_layout.h\"\n"
        "\n"
        "const GameRamLayout g_game_layout = {\n"
        "    .game_mode_addr     = 0x%08Xu,\n"
        "    .vint_runcount_addr = 0x%08Xu,\n"
        "    .vint_routine_addr  = 0x%08Xu,\n"
        "    .plc_pending_addr   = 0x%08Xu,\n"
        "    .initial_ssp        = 0x%08Xu,\n"
        "    .vbla_stack         = 0x%08Xu,\n"
        "    .intr_stack         = 0x%08Xu,\n"
        "    .player_object_addr = 0x%08Xu,\n"
        "    .level_modes        = {",
        output_path,
        L->game_mode_addr, L->vint_runcount_addr, L->vint_routine_addr,
        L->plc_pending_addr, L->initial_ssp, L->vbla_stack, L->intr_stack,
        L->player_object_addr);
    for (int i = 0; i < L->level_mode_count; i++)
        fprintf(f, "%s 0x%02Xu", i ? "," : "", L->level_modes[i]);
    fprintf(f, " },\n"
        "    .level_mode_count   = %d,\n"
        "};\n", L->level_mode_count);

    fclose(f);
    printf("[GenesisRecomp] Emitted %s\n", output_path);
    return true;
}
