#include "module_emit.h"
#include "module_entries.h"
#include "module_seeds.h"
#include "cdi_sha256.h"
#include "code_generator.h"
#include "codegen_diag.h"
#include "function_finder.h"
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#ifdef _WIN32
#include <direct.h>
#define make_directory(p) _mkdir(p)
#else
#include <sys/stat.h>
#define make_directory(p) mkdir(p,0777)
#endif

bool cdi_emit_modules(CdiDisc *disc, const Os9Module *modules, int count,
                      const char *directory, const char *module_filter,
                      bool named_offset_pairs, const char *seed_path) {
    enum { MAX_FILES=2048, MAX_MODULES=512 };
    if (count<0 || count>MAX_MODULES) return false;
    CdiModuleSeeds seeds={0};
    if (!cdi_module_seeds_read(seed_path,&seeds)) return false;
    CdiFile *files=calloc(MAX_FILES,sizeof *files);
    uint8_t (*digests)[32]=calloc(MAX_MODULES,32);
    if (!files || !digests) { free(files);free(digests);cdi_module_seeds_free(&seeds);return false; }
    int nfiles=cdi_list_files(disc,files,MAX_FILES), emitted=0;
    if (nfiles<0 || nfiles>MAX_FILES ||
        (make_directory(directory)!=0 && errno!=EEXIST)) {
        free(files);free(digests);cdi_module_seeds_free(&seeds);return false;
    }
    char manifest_path[1200];
    if (snprintf(manifest_path,sizeof manifest_path,"%s/module_manifest.c",directory)>=sizeof manifest_path) {
        free(files);free(digests);cdi_module_seeds_free(&seeds);return false;
    }
    FILE *manifest=fopen(manifest_path,"w");
    if (!manifest) { free(files);free(digests);cdi_module_seeds_free(&seeds);return false; }
    fprintf(manifest,"/* AUTO-GENERATED by CdiRecomp. DO NOT EDIT. */\n#include \"cdi_native.h\"\n");
    uint8_t *file_data=NULL;
    const CdiFile *cached=NULL;
    int indices[MAX_MODULES];
    bool ok=true;
    for (int i=0;i<count && ok;i++) {
        const Os9Module *m=&modules[i];
        if (m->lang!=1 || (m->type!=1 && m->type!=2) ||
            (module_filter && strcmp(module_filter,m->name))) continue;
        if (!m->crc_ok) { fprintf(stderr,"[modules] invalid CRC: %s\n",m->name);ok=false;break; }
        const CdiFile *file=NULL;
        for (int j=0;j<nfiles;j++) if (!strcmp(files[j].path,m->file_path)) { file=&files[j];break; }
        if (!file || m->file_offset>file->size || m->size>file->size-m->file_offset || m->size<0x38) {
            ok=false;break;
        }
        if (file!=cached) {
            free(file_data);file_data=malloc(file->size);cached=file;
            if (!file_data || !cdi_read_file_form1(disc,file,file_data,file->size)) { ok=false;break; }
        }
        uint8_t *data=file_data+m->file_offset;
        uint8_t digest[32];cdi_sha256(data,m->size,digest);
        bool duplicate=false;
        for (int j=0;j<emitted;j++) if (!memcmp(digests[j],digest,32)) { duplicate=true;break; }
        if (duplicate) continue;
        uint32_t entries[32768+256],metadata_end;
        int nentries=cdi_module_entries(data,m->size,m->type,named_offset_pairs,
                                        entries,256,&metadata_end);
        if (nentries<1) {
            fprintf(stderr,"[modules] unsupported/invalid entry layout: %s (Subr needs --subr-exports named-offset32)\n",m->name);
            ok=false;break;
        }
        if (!cdi_module_seeds_merge(&seeds,digest,metadata_end,m->size-3,
                                    entries,sizeof entries/sizeof *entries,&nentries)) {
            fprintf(stderr,"[modules] invalid seed offset for %s\n",m->name);
            ok=false;break;
        }
        uint32_t entry=entries[0];
        GenesisRom rom={0};rom.rom_data=data;rom.rom_size=m->size-3;rom.initial_pc=entry;
        GameConfig cfg={0};game_config_init_empty(&cfg);
        cfg.function_aliases=true;cfg.async_resume_entries=true;cfg.trap0_inline_service_word=true;
        cfg.extra_funcs=entries;cfg.extra_func_count=nentries;
        ProtectedRange header={0,metadata_end};cfg.protected_ranges=&header;cfg.protected_range_count=1;
        FunctionList functions={0};function_finder_run_module(&rom,&functions,&cfg);
        AnnotationTable annotations={0};
        char symbol[64],full[1200],dispatch[1200];
        snprintf(symbol,sizeof symbol,"cdi_module_%03d",i);
        if (snprintf(full,sizeof full,"%s/%s_full.c",directory,symbol)>=sizeof full ||
            snprintf(dispatch,sizeof dispatch,"%s/%s_dispatch.c",directory,symbol)>=sizeof dispatch) {
            function_list_free(&functions);ok=false;break;
        }
        printf("[modules] %s %d entry(s), first+$%X -> %s (%d functions)\n",m->name,nentries,entry,symbol,functions.count);
        ok=codegen_emit_module(&rom,&functions,full,dispatch,&annotations,&cfg,symbol);
        int diagnostics=codegen_diag_total();
        if (diagnostics) { codegen_diag_print_summary(stderr);ok=false; }
        function_list_free(&functions);
        if (!ok) break;
        memcpy(digests[emitted],digest,32);indices[emitted++]=i;
        fprintf(manifest,"int %s_has_offset(uint32_t);\nint %s_dispatch(uint32_t,uint32_t);\n",symbol,symbol);
    }
    if (!module_filter) for (size_t i=0;i<seeds.count;i++) if (!seeds.items[i].matched) {
        fprintf(stderr,"[modules] seed identity does not match any emitted module\n");
        ok=false;break;
    }
    if (!emitted) ok=false;
    if (ok) {
        fprintf(manifest,"const CdiNativeModule g_cdi_native_modules[] = {\n");
        for (int j=0;j<emitted;j++) {
            int i=indices[j];
            /* Validated OS-9 names may contain C string metacharacters. */
            fprintf(manifest,"  {\"");
            for (const unsigned char *p=(const unsigned char *)modules[i].name;*p;p++)
                fprintf(manifest,"\\%03o",*p);
            fprintf(manifest,"\", %uu, {",modules[i].size);
            for (unsigned b=0;b<32;b++) fprintf(manifest,"%s0x%02X",b?",":"",digests[j][b]);
            fprintf(manifest,"}, cdi_module_%03d_has_offset, cdi_module_%03d_dispatch},\n",i,i);
        }
        fprintf(manifest,"};\nconst size_t g_cdi_native_module_count = %d;\n",emitted);
    } else {
        fprintf(manifest,"#error CdiRecomp module emission failed; regenerate after fixing diagnostics\n");
    }
    if (fclose(manifest)!=0) ok=false;
    if (ok) {
        char sources_path[1200];
        if (snprintf(sources_path,sizeof sources_path,"%s/module_sources.cmake",directory)>=sizeof sources_path)
            ok=false;
        else {
            FILE *sources=fopen(sources_path,"w");
            if (!sources) ok=false;
            else {
                fprintf(sources,"# AUTO-GENERATED by CdiRecomp. DO NOT EDIT.\nset(CDI_NATIVE_MODULE_FILES\n  module_manifest.c\n");
                for (int j=0;j<emitted;j++)
                    fprintf(sources,"  cdi_module_%03d_full.c\n  cdi_module_%03d_dispatch.c\n",indices[j],indices[j]);
                fprintf(sources,")\n");
                if (fclose(sources)!=0) ok=false;
            }
        }
    }
    if (!ok) {
        /* Also poison a stale manifest if writing the source list failed. */
        FILE *failed=fopen(manifest_path,"a");
        if (failed) { fputs("#error CdiRecomp module emission was incomplete\n",failed);fclose(failed); }
    }
    free(file_data);free(files);free(digests);cdi_module_seeds_free(&seeds);
    return ok;
}
