# Run after linking. Hash exactly the configured runtime inputs, plus the
# linked binary, so acceptance tools can reject a stale local executable.
if(NOT DEFINED PROVENANCE_INPUTS OR NOT DEFINED RUNTIME)
    message(FATAL_ERROR "build provenance requires an input list and runtime")
endif()
include("${PROVENANCE_INPUTS}")
function(json_escape input output)
    string(REPLACE "\\" "\\\\" value "${input}")
    string(REPLACE "\"" "\\\"" value "${value}")
    string(REPLACE "\n" "\\n" value "${value}")
    string(REPLACE "\r" "\\r" value "${value}")
    string(REPLACE "\t" "\\t" value "${value}")
    set(${output} "${value}" PARENT_SCOPE)
endfunction()
file(SHA256 "${RUNTIME}" binary_hash)
json_escape("${PROVENANCE_COMPILER}" compiler)
json_escape("${PROVENANCE_OPTIONS}" options)
set(result "{\n  \"schema\": 1,\n  \"runtime_sha256\": \"${binary_hash}\",\n  \"compiler\": \"${compiler}\",\n  \"options\": \"${options}\",\n  \"inputs\": [")
set(separator "")
list(REMOVE_DUPLICATES PROVENANCE_FILES)
list(SORT PROVENANCE_FILES)
foreach(input IN LISTS PROVENANCE_FILES)
    if(NOT EXISTS "${input}")
        message(FATAL_ERROR "build provenance input missing: ${input}")
    endif()
    file(SHA256 "${input}" hash)
    json_escape("${input}" path)
    string(APPEND result "${separator}\n    {\"path\": \"${path}\", \"sha256\": \"${hash}\"}")
    set(separator ",")
endforeach()
string(APPEND result "\n  ]\n}\n")
file(WRITE "${RUNTIME}.build.json" "${result}")
